services:
  - type: web
    name: github-rag-backend
    runtime: python

    rootDir: scripts     # <---- THIS MAKES scripts THE WORKING DIRECTORY

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn repo_processor:app --host 0.0.0.0 --port 10000

    envVars:
      - key: OPENAI_API_KEY
        sync: false

    disk:
      name: vector-db
      mountPath: /opt/render/project/src/scripts/vector_store
      sizeGB: 1
